from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import os
import requests
import json
import time
from dotenv import load_dotenv

load_dotenv()

router = APIRouter()

API_KEY = os.getenv("GEMINI_API_KEY")

def get_available_model(api_key: str) -> str:
    """Get an available Gemini model that supports generateContent."""
    return "gemini-flash-latest"

class GenerateContentRequest(BaseModel):
    topic: str
    level: str

@router.post("/generate-content")
async def generate_content(request: GenerateContentRequest):
    """
    Generate educational content using Gemini AI via direct API call
    """
    if not API_KEY:
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY not configured")
    
    try:
        # Dynamically get an available model
        model_name = get_available_model(API_KEY)
        gemini_url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent"
        
        prompt = f"""You are an expert educator.

Create detailed, high-quality learning content on the topic: "{request.topic}" for {request.level} level learners.

Structure the response clearly with the following sections:

1. Introduction  
- Explain the topic in a simple and clear way  

2. Core Concepts  
- Cover all important concepts in depth  
- Use bullet points where helpful  

3. Detailed Explanation  
- Explain how things work step-by-step  
- Keep it easy to understand but informative  

4. Examples  
- Provide practical examples  
- If the topic is technical, include code examples  
- If not, include real-world examples  

5. Summary  
- Briefly summarize key takeaways  

Guidelines:
- Keep the explanation clear, structured, and readable  
- Avoid unnecessary complexity  
- Adapt explanation style based on the topic  
- Do not include quizzes or questions"""

        # Prepare the request payload
        payload = {
            "contents": [{
                "parts": [{"text": prompt}]
            }]
        }
        
        # Make the API call with retries
        max_retries = 3
        base_delay = 0.5
        for attempt in range(max_retries):
            try:
                url = f"{gemini_url}?key={API_KEY}"
                response = requests.post(url, json=payload, timeout=60)
                break  # Success, exit retry loop
            except requests.exceptions.Timeout:
                if attempt == max_retries - 1:
                    raise  # Last attempt, re-raise
                time.sleep(base_delay * (2 ** attempt))  # Exponential backoff
        
        if response.status_code != 200:
            error_detail = response.json() if response.text else "Unknown error"
            raise Exception(f"API returned {response.status_code}: {error_detail}")
        
        result = response.json()
        
        if "candidates" not in result or not result["candidates"]:
            raise Exception("No content generated by AI")
        
        # Extract the generated text
        generated_text = result["candidates"][0]["content"]["parts"][0]["text"]
        
        return {"content": generated_text}
    
    except requests.exceptions.Timeout:
        raise HTTPException(status_code=504, detail="Request timed out. Please try again.")
    except requests.exceptions.RequestException as e:
        raise HTTPException(status_code=500, detail=f"Network error: {str(e)}")
    except Exception as e:
        print(f"Error details: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to generate content: {str(e)}")